# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '无限循环滚动SF' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 无限循环滚动SF

  target '无限循环滚动SFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '无限循环滚动SFUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Kingfisher', '~> 3.2.1'
end
